# Generated by Django 4.2.6 on 2023-11-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTRNT', '0002_alter_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
