# Generated by Django 4.2.6 on 2023-11-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RESTRNT', '0003_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('prdctprc', models.BigIntegerField()),
                ('desc', models.TextField()),
                ('desc2', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='static')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RESTRNT.productcategory')),
            ],
        ),
    ]
