# Generated by Django 4.2.6 on 2023-11-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTRNT', '0005_alter_post_img_alter_product_img_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
