# Generated by Django 4.2.6 on 2023-11-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTRNT', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(max_length=250),
        ),
    ]
