# Generated by Django 4.2.6 on 2023-11-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTRNT', '0007_profile_image_alter_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='UserImage'),
        ),
    ]
