# Generated by Django 4.2.6 on 2023-11-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTRNT', '0009_bookatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookatable',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='bookatable',
            name='username',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
