# Generated by Django 4.2.6 on 2023-11-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTRNT', '0010_bookatable_email_bookatable_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='noOfperson',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
