# Generated by Django 4.2.6 on 2023-11-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTRNT', '0013_alter_bookatable_noofperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
